/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author kritimakhatri
 */
public class assessmentScreen extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public assessmentScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        html = new javax.swing.JTextField();
        java = new javax.swing.JTextField();
        python = new javax.swing.JTextField();
        pythonbtn = new javax.swing.JButton();
        htmlbtn = new javax.swing.JButton();
        javabtn = new javax.swing.JButton();
        cpp = new javax.swing.JTextField();
        cppbtn = new javax.swing.JButton();
        pythonbtn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTextField2.setText("ASSESSMENT 1");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setFocusTraversalKeysEnabled(false);
        jPanel1.setFocusable(false);
        jPanel1.setFont(new java.awt.Font("Savoye LET", 0, 13)); // NOI18N
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Apple Chancery", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ONLINE ASSESSMENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 488, 89));

        html.setEditable(false);
        html.setBackground(new java.awt.Color(158, 89, 170));
        html.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        html.setText("ASSESSMENT 3");
        html.setFocusTraversalKeysEnabled(false);
        html.setFocusable(false);
        html.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(html, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 190, 100));

        java.setEditable(false);
        java.setBackground(new java.awt.Color(158, 89, 170));
        java.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        java.setText("ASSESSMENT 2");
        java.setFocusTraversalKeysEnabled(false);
        java.setFocusable(false);
        java.setVerifyInputWhenFocusTarget(false);
        java.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javaActionPerformed(evt);
            }
        });
        jPanel1.add(java, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 140, 190, 100));

        python.setEditable(false);
        python.setBackground(new java.awt.Color(158, 89, 170));
        python.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        python.setText("ASSESSMENT 1");
        python.setFocusTraversalKeysEnabled(false);
        python.setFocusable(false);
        python.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(python, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, 100));

        pythonbtn.setText("PYTHON");
        pythonbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pythonbtnActionPerformed(evt);
            }
        });
        jPanel1.add(pythonbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, 60));

        htmlbtn.setText("HTML");
        htmlbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htmlbtnActionPerformed(evt);
            }
        });
        jPanel1.add(htmlbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 190, 60));

        javabtn.setText("JAVA");
        javabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javabtnActionPerformed(evt);
            }
        });
        jPanel1.add(javabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 240, 190, 60));

        cpp.setEditable(false);
        cpp.setBackground(new java.awt.Color(158, 89, 170));
        cpp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpp.setText("ASSESSMENT 4");
        cpp.setFocusTraversalKeysEnabled(false);
        cpp.setFocusable(false);
        cpp.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(cpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 380, 190, 100));

        cppbtn.setText("CPP");
        cppbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cppbtnActionPerformed(evt);
            }
        });
        jPanel1.add(cppbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 480, 190, 60));

        pythonbtn1.setText("PYTHON");
        pythonbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pythonbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(pythonbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, 60));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Sinhala MN", 0, 20)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/icons8-close-window-30.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, -1, 40));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/icons8-start-40.png"))); // NOI18N
        jButton1.setText("Strat Quiz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 160, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1200, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void cppbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cppbtnActionPerformed
        // TODO add your handling code here:
        new Quiz().setVisible(true);
    }//GEN-LAST:event_cppbtnActionPerformed

    private void javabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javabtnActionPerformed
        // TODO add your handling code here:
        new Quiz().setVisible(true);
    }//GEN-LAST:event_javabtnActionPerformed

    private void htmlbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htmlbtnActionPerformed
        // TODO add your handling code here:
        new Quiz().setVisible(true);
    }//GEN-LAST:event_htmlbtnActionPerformed

    private void pythonbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pythonbtnActionPerformed
        // TODO add your handling code here:
        new Quiz().setVisible(true);
    }//GEN-LAST:event_pythonbtnActionPerformed

    private void javaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_javaActionPerformed

    private void pythonbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pythonbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pythonbtn1ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
                // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
this.dispose();
             // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new Quiz().setVisible(true);    }//GEN-LAST:event_jButton1ActionPerformed
             
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//
                new assessmentScreen().setVisible(true);
    
        };
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cpp;
    private javax.swing.JButton cppbtn;
    private javax.swing.JTextField html;
    private javax.swing.JButton htmlbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField java;
    private javax.swing.JButton javabtn;
    private javax.swing.JTextField python;
    private javax.swing.JButton pythonbtn;
    private javax.swing.JButton pythonbtn1;
    // End of variables declaration//GEN-END:variables
}
