/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.*;

import database.DbConnection;

/**
 *
 * @author HP
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        tfpass = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnlogin = new javax.swing.JButton();
        btnforgotpass = new javax.swing.JButton();
        btnsignup = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/login.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 160, 510, 440);

        jPanel1.setBackground(new java.awt.Color(152, 200, 231));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 2, 30)); // NOI18N
        jLabel4.setText("Log In!");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 60, 140, 42);

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 2, 25)); // NOI18N
        jLabel3.setText("Welcome Back,");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(14, 14, 210, 40);

        tfusername.setBackground(new java.awt.Color(152, 200, 231));
        tfusername.setFont(new java.awt.Font("Leelawadee UI", 0, 17)); // NOI18N
        tfusername.setText("Username or email");
        tfusername.setBorder(null);
        tfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusernameActionPerformed(evt);
            }
        });
        jPanel1.add(tfusername);
        tfusername.setBounds(120, 160, 260, 30);

        tfpass.setBackground(new java.awt.Color(152, 200, 231));
        tfpass.setText("jPasswordField1");
        tfpass.setBorder(null);
        tfpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpassActionPerformed(evt);
            }
        });
        jPanel1.add(tfpass);
        tfpass.setBounds(126, 227, 209, 22);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(120, 190, 211, 10);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(126, 255, 209, 10);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/icons8-user-30.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 160, 40, 40);

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel9.setText("Don't have an account yet?");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 370, 152, 14);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(450, 290, 107, 19);

        btnlogin.setFont(new java.awt.Font("Leelawadee UI", 0, 17)); // NOI18N
        btnlogin.setText("LOG IN");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin);
        btnlogin.setBounds(80, 310, 420, 50);

        btnforgotpass.setBackground(new java.awt.Color(152, 200, 231));
        btnforgotpass.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        btnforgotpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/icons8-alzheimer-40.png"))); // NOI18N
        btnforgotpass.setText("Forgot Password?");
        btnforgotpass.setBorder(null);
        btnforgotpass.setBorderPainted(false);
        btnforgotpass.setContentAreaFilled(false);
        btnforgotpass.setDefaultCapable(false);
        btnforgotpass.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/icons8-alzheimer-40.png"))); // NOI18N
        btnforgotpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnforgotpassActionPerformed(evt);
            }
        });
        jPanel1.add(btnforgotpass);
        btnforgotpass.setBounds(410, 260, 140, 30);

        btnsignup.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        btnsignup.setText("Sign Up");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        jPanel1.add(btnsignup);
        btnsignup.setBounds(10, 390, 140, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/icons8-secure-40-2.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(66, 227, 40, 31);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(610, 180, 580, 460);

        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 190, 0, 0);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/logo1_1.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(530, 0, 154, 138);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        setSize(new java.awt.Dimension(1200, 654));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfusernameActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed

        String password=new String(tfpass.getPassword());
        String username=tfusername.getText();
        DbConnection db=new DbConnection();

        if(evt.getSource()==btnlogin)
            {
             
                System.out.println("Username,Pwd:"+username+","+password);

                //The entered username and password are sent via "checkLogin()" which return boolean
                if(!db.checkLogin(username, password))
                    
                {
                    //a pop-up box
                    JOptionPane.showMessageDialog(null, "Wrong password. Try again","Failed!!",
                            JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    //a pop-up box
                    JOptionPane.showMessageDialog(null, "You have logged in successfully","Success",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            
        
            
        
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsignupActionPerformed

    private void btnforgotpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnforgotpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnforgotpassActionPerformed

    private void tfpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnforgotpass;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsignup;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField tfpass;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
